### PR TITLE
Add algebraic form

### PR DESCRIPTION
**Pull request by CK-Explorer**
Added a new member to the Parameters struct to store all 10 coefficients of the ellipsoid equation in algebraic form.

And in Parameters::print(), added a line to print all 10 coefficients .

### CODE REVIEW

**Comment by BenjaminNavarro** [comment]
Thanks for the contribution.

Can you tell me what's the use case for this?

Also, the problem I have with this is that there is no enforced invariant between the coefficients and `center`/`radii`. So if someone passes this new `Parameters` struct to the `generate` function then they might expect different things from it. It could use `center`/`radii` as it does right now or use the coefficients vector, which wouldn't work.

So I would be more inclined in adding an overload to the `fit` function with an output parameter to retrieve the coefficients when needed. Doing it like this has the benefit to neither break the API or the ABI.

**Comment by CK-Explorer** [comment]
Hi, I use this library to perform magnetometer and accelerometer calibration. This process requires the center of the ellipsoid and the 6 coefficients of the shifted ellipsoid, which can be determined from the 10 coefficients of the original ellipsoid.

Based on your request, I have overloaded the ```fit``` function with a functor as an input, which allows user to obtain those 10 coefficients, and I have reverted back to the same code as before for other parts.

Please let me know if I need to have any additional modification.

**Comment by CK-Explorer** [comment]
Yeah, this is a better solution and I just made things so complicated. So, are you going to add this in your code, or do you want me to modify my code?

**Comment by CK-Explorer** [comment]
Thanks for letting me to contribute. I have made the changes, please let me know if there is anything to add or correct.

**Comment by BenjaminNavarro** [comment]
Perfect, thanks a lot for the contribution !

**Pull request merged**
